### ISSUE TITLE
datadog does not support fluentd multiple workers

### ISSUE THREAD

**Issue by dpgaspar** [DataDog/fluent-plugin-datadog#17]
**Describe what happened:**
When using fluentd 1.2.6 with multiple workers:

```
<system>
   log_level info
    workers 4
</system>
```
this plugin does not support the multiple workers option
```
[error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Plugin 'datadog' does not support multi workers configuration (Fluent::DatadogOutput)"
```

when using <worker> tag on the datadog plugin output match:
```
<worker 0>
  <match raw.nginx.**>
    @id raw.nginx.0
    @log_level debug
    @type datadog
           ....
  </match>
</worker>
```
No logs are sent to Datadog, and no error is reported

**Describe what you expected:**
datadog support support for multiple workers

**Steps to reproduce the issue:**
Use the above configurations

**Additional environment details (Operating System, Cloud provider, etc):**
OS: AMZN Linux
Fluentd: 1.2.6
fluent-plugin-datadog (0.10.4)

Thank you!

**Comment by tmichelet** [comment]
Thanks for reporting!
