### ISSUE TITLE
Use of deprecated API

### ISSUE THREAD

**Issue by achntrl** [DataDog/fluent-plugin-datadog#19]
**Describe what happened:**

We use BufferedOutput: 

https://github.com/fluent/fluentd/blob/master/lib/fluent/compat/output.rb#L205

That will be deprecated at some point (don't know when)

We should proactively migrate to the new API and make sure nothing breaks before it bites us and we're forced to migrate

cf https://www.fluentd.org/blog/fluentd-v0.14.12-has-been-released in the "Making plugins available with multi process workers" section

**Comment by gaetan-deputier** [comment]
Resolved with 0.12.0
