### ISSUE TITLE
failed to flush buffer since 0.12.1

### ISSUE THREAD

**Issue by olalofgren** [DataDog/fluent-plugin-datadog#36]
Since 0.12.1 i cannot export logs to Datadog.
It only logs the error at every interval.
`{"time":"2020-02-26 10:02:29","level":"warn","message":"[awesome_agent] failed to flush the buffer. retry_time=0 next_retry_seconds=2020-02-26 10:38:30 +0100 chunk=\"59f775b38d5a14c849c68c03572c62be\" error_class=Net::HTTP::Persistent::Error error=\"too many connection resets (due to end of file reached - EOFError) after 0 requests on 70266899361300, last used 1582709909.8593261 seconds ago\"","worker_id":0}`

I'm running td-agent 3.6.0 on Ubuntu 16.04

"Fixed" the problem by downgrading to 0.11.1

**Comment by gaetan-deputier** [comment]
Hey, thanks for the report. We're going to look at it.

**Comment by bengtrj** [comment]
I'm having the same error since I updated to 0.12. Here's my config:
```
<match **.us>
  @type             datadog
  @id               'REDACTED'

  @log_level        "#{ENV.fetch('DD_LOGS_LOG_LEVEL', 'info')}"
  host              "#{ENV.fetch('DD_LOGS_HOST_US')}"
  ssl_port          "#{ENV.fetch('DD_LOGS_PORT_US')}"

  api_key           "#{ENV['DD_LOGS_API_KEY']}"
  dd_source         'REDACTED'

  dd_tags           "#{ENV.fetch('DD_CUSTOM_TAGS', '')}"
  max_retries       10

  <buffer>
    @type              file
    path               /tmp/fluentd_datadog_buffer_us
    total_limit_size   "#{ENV.fetch('TOTAL_LIMIT_SIZE', '1024MB')}"
    chunk_limit_size   "#{ENV.fetch('CHUNK_LIMIT_SIZE', '256MB')}"
    flush_thread_count "#{ENV.fetch('FLUSH_THREAD_COUNT', 1)}"
    flush_mode         "#{ENV.fetch('FLUSH_MODE', 'interval')}"
    flush_interval     "#{ENV.fetch('FLUSH_INTERVAL', '60s')}"


    retry_type         "#{ENV.fetch('RETRY_TYPE', 'exponential_backoff')}"
    retry_timeout      "#{ENV.fetch('RETRY_TIMEOUT', '10m')}"
    retry_max_interval "#{ENV.fetch('RETRY_MAX_INTERVAL', '30')}"
    overflow_action    "#{ENV.fetch('OVERFLOW_ACTION', 'drop_oldest_chunk')}"
  </buffer>
</match>
```

Plus, can you give me some feedback on the `chunk_limit_size`, do you think 256MB is too much? I'm asking because on this issue https://github.com/DataDog/fluent-plugin-datadog/issues/38 you folks recommend 5MB.

**Comment by gaetan-deputier** [comment]
Hey @bengtrj ,
What are the `host` and `ssl_port` you are using? If you've upgraded to 0.12 and are specifying a TCP specific endpoint you might get this issue.

For chunks, we recommend using:
```          
          chunk_limit_size 5m
          chunk_limit_records 500
```

**Comment by jszwedko** [comment]
Closing due to lack of response.
